# Config file for automatic testing at travis-ci.org

branches:
 only:
  - master

language: python

matrix:
  include:
    - os: linux
      python: "3.4"

    - os: linux
      python: "3.3.5"

    - os: linux
      python: "2.7"

    - os: osx
      language: generic
      env:
        - PYTHONVERSION=3.4.5

    - os: osx
      language: generic
      env:
        - PYTHONVERSION=3.3.6

    - os: osx
      language: generic
      env:
        - PYTHONVERSION=2.7.12

cache:
  directories:
    - $HOME/.pyenv/versions/3.4.5
    - $HOME/.pyenv/versions/3.3.6
    - $HOME/.pyenv/versions/2.7.12

before_install:
  - |
    git clone git://github.com/scikit-build/scikit-ci -b $TRAVIS_BRANCH ../boostrap-scikit-ci
    pip install -U ../boostrap-scikit-ci
  - pip install scikit-ci-addons==0.3.0
  - ci_addons --install ../addons

# scikit-ci-yml.rst: start
install:
  - ci install

script:
  - ci test

after_success:
  - ci after_test
# scikit-ci-yml.rst: end
